spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://realtime-chatapp-auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://realtime-chatapp-user-service
          predicates:
            - Path=/users/**
        - id: chat-service
          uri: lb://realtime-chatapp-message-service
          predicates:
            - Path=/chat/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true